### ISSUE TITLE
Cumulative dps boost is calculated incorrectly

### ISSUE THREAD

**Issue by DarkFenX** [StephenSwat/eve-abyssal-market#3]
https://mutaplasmid.space/module/1029125282125/
12.9% dmg modifier, 7.9% rof modifier shows as 21.9% dps boost (possibly due to 1.129×1.079 = 1.218191)

Actual dps boost is, however: 1.129÷(1−0.079) = 1.225841477

**Comment by StephenSwat** [comment]
I understand how this can be confusing but I _think_ it is shown correctly on the website. Personally I find the way the game represents rate of fire bonuses pretty bad because it doesn't show an increase in the rate of fire but a decrease in the reload time of modules (I see you're a Pyfa dev so I don't think I have to explain this). 

What I do on the website is take the value shown in game (7.33% for this module) and show 1÷(1-0.0733) = 7.9%. This value can be directly multiplied by the damage multiplier to get the DPS boost.

Because I think the value shown on the website is correct, I'm going to mark this as "won't fix" for now. But if you think it would be better to show the same value as the game I may change it in the future.

**Comment by DarkFenX** [comment]
Yes i think having value consistent with ingame is important for integration sake. I have one use-case I'm dealing with on a regular basis:

I am planning to fit some mutated mods to my leshak. To see what kind of stats i will have in the end - I am entering mutated values to Pyfa. However, I am unable to fetch actual rof modifier without doing additional conversion step x = (1−1÷(1+y÷100))×100 where x is the value i want to get and y is value shown on mutaplasmid.space. Pyfa doesn't take this convention out of the blue - it's EVE client which forces it.

There are numerous less obvious cases, e.g. I'm often using calculator to calculate various things - like spoolup time improvement with new damage mod vs old damage mod, w/o entering full stats to pyfa. Also, seeing that RoF value can go beyond limits set in game confused me a lot. For instance, t2 entropic sink rof modifier with decayed mutation can't go beyond value 7.41% "eve rof", but I've seen it as high as 7.9% on mutaplasmid.space. I poked few of my buddies to make ingame screenshot of contract - and value there was different.

So, all-in-all, i think it's not necessarily a bad thing, but some hints showing that it's "real rof", not "eve rof" would definitely help.

**Comment by StephenSwat** [comment]
This is a good point. If we're talking about compatibility with Pyfa do you think it would be better to show damage multiplier as 1.20x instead of 20% as well?

**Comment by DarkFenX** [comment]
Probably yes, although this conversion is much more trivial and i don't mind doing it at all.

Regarding user-friendly values - i think that showing final cumulative boost is enough for user to get an impression of how strong this mutation is.

**Comment by DarkFenX** [comment]
tyvm <3
