### ISSUE TITLE
Mutated module export format

### ISSUE THREAD

**Issue by DarkFenX** [StephenSwat/eve-abyssal-market#4]
A while ago I've implemented [mutated stats import/export](https://github.com/pyfa-org/Pyfa/issues/1707) as EFT format extension for Pyfa. Likewise, format for stand-alone modules can be implemented as well.

```
Entropic Radiation Sink II
  Decayed Entropic Radiation Sink Mutaplasmid
  cpu 36.08, damageMultiplier 1.135, speedMultiplier 0.9261
```
or without additional indentation:
```
Entropic Radiation Sink II
Decayed Entropic Radiation Sink Mutaplasmid
cpu 36.08, damageMultiplier 1.135, speedMultiplier 0.9261
```
Mutaplasmid.space could have a way to export stats of desired module into clipboard, and i could easily implement a way to paste that into active pyfa fit (supposedly, by just pressing ctrl-v).

What are your thoughts on this feature in general and on proposed format specifically?

One of benefits of wider adoption of such format (or any alternatives you can propose) - maybe sooner or later CCP will adopt it as well, just like they did with EFT format. Better integration between game and external tools leads to better user experience.

**Comment by StephenSwat** [comment]
Great idea! I like the format you propose, because:

1. It is similar to what is already in Pyfa
2. It is human readable and editable
3. It appears to use the standard names that CCP also uses
4. It allows inheritance from the original module so module specifications are compact

I will start work on adding a "Copy to Pyfa" button. I believe it would be good to add this button to the module lists (i.e. https://mutaplasmid.space/type/49730/) and also to the page for each module (i.e. https://mutaplasmid.space/module/1029164458712/).

**Comment by DarkFenX** [comment]
Ok cool. Just don't enable it until this is implemented in pyfa & this change is released.

**Comment by StephenSwat** [comment]
Alright I've got the feature ready to go in a branch. Please let me know when Pyfa launches this functionality and I will deploy the export button.

**Comment by blitzmann** [comment]
@StephenSwat just merged in the PR on pyfa's side, but haven't made a release yet. Will let you know when we've got a release out which supports this. Shouldn't be more than a couple days, if that. Looks awesome!

**Comment by DarkFenX** [comment]
@StephenSwat heads up, blitzmann is going to make release today - everything is ready for it. He will post here when it's up.

**Comment by blitzmann** [comment]
@StephenSwat pyfa release is out :)

**Comment by StephenSwat** [comment]
Thanks for the heads up lads! Keep up the fantastic work on Pyfa!
